### ISSUE TITLE
[FireStick gen.2] ExoPlayer and ExoPlayer Amazon Port crash after upgrade Fire OS to version 5.2.4.0 (5.2.4.1, 5.2.6.2)

### ISSUE THREAD

**Issue by kristurek** [amzn/exoplayer-amazon-port#44] opened 2018-05-02 17:08 UTC
### Issue description
After auto update FireStick to version 5.2.4.0 (5.2.4.1, 5.2.6.2) ExoPlayer crash when i try play stream IPTV. 
Before update, FireStick OS has version 5.2.2.0 and everything worked perfect.
Additionally sample stream i'm tested on VLC (FireStick) and the same results, player not work correctly.
On other devices like Samsung S6 Egde, Nexus 4, Samsung Galaxy Tab works perfect.

This seems to be a system fault

05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: java.lang.IllegalStateException
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1055)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1064)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:599)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.doSomeWork(ExoPlayerImplInternal.java:522)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:305)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.Handler.dispatchMessage(Handler.java:98)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.Looper.loop(Looper.java:135)
05-02 09:16:42.292  7788  7940 E ExoPlayerImplInternal: 	at android.os.HandlerThread.run(HandlerThread.java:61)

and

05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] Input picture is over MAX.
05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] Insert PTS error
05-02 09:16:42.285   165  7947 E MtkOmxVdec: [0xb7b888b0] something wrong when decoding....
05-02 09:16:42.285   165  7947 D MtkOmxVdec: [0xb7b888b0] MtkOmxVdecDecodeThread terminated pVdec=0xB7B888B0
05-02 09:16:42.286  7788  7945 E ACodec  : [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001008)
05-02 09:16:42.286  7788  7945 E ACodec  : signalError(omxError 0x80001008, internalError -2147483648)
05-02 09:16:42.286  7788  7944 E MediaCodec: Codec reported err 0x80001008, actionCode 0, while in state 6

### Reproduction steps
Add to media.exolist.json downloaded sample and run demo, after 2-5s player crash.
`{
    "name": "Test stream",
    "samples": [
      {
        "name": "HD",
        "uri": "/storage/sdcard0/Download/hd.mp4"
      }
    ]
  },
`

### Link to test content
Sample stream https://www.dropbox.com/s/8yhtgwjx4jyo6vz/hd.mp4?dl=0

### Version of ExoPlayer being used
Current FireStick Software version Fire OS 5.2.6.2 (587700720)
Fire TV Home Version 6.0.0.4-101
Fresh ExoPlayer from GitHub 2.7.3 or ExoPlayer Amazon Port 2.7.1

### A full bug report captured from the device
Bugreport https://www.dropbox.com/s/1t5qrakqbmbkvfs/bugreport_tvp_hd_amazon.txt?dl=0
Log file https://www.dropbox.com/s/8yl3eag5fr2dy3r/log_amazon.txt?dl=0

Thanks for any help, and sorry for my english

Regards

**Comment by peddisri** [comment] 2018-05-17 12:40
Fixed in next system OTA. Will keep you updated on timelines.

**Comment by kristurek** [comment] 2018-05-18 15:36
ok, thank you very much

**Comment by alex-schwartzman** [comment] 2018-05-31 14:26
@peddisri is there any OTA problems spotted for the recent upgrade of FireTV gen 3, which happened around May 16th?

I'm now watching Google Analytics and I observe some intermittent issues with failure to start the playback, which started occurring on Week20. 

I cannot reproduce this issue in the lab, so all the information above is just a gossip and wild guess. However, if you would be able to shed a light on that, I'd greatly appreciate that.

**Comment by kristurek** [comment] 2018-06-05 16:57
This bug is on Fire Stick Gen.2, i don't know nothing about Fire TV gen.3.
I tested attached sample on the 3 FireStick's, always same results, app crashed after 3-5 seconds.

**Comment by peddisri** [comment] 2018-06-11 03:33
I'm tracking Gen3 issues in https://github.com/amzn/exoplayer-amazon-port/issues/46 .

@alex-schwartzman  can you upload the logs to that issue when u are able to repro it.

**Comment by peddisri** [comment] 2018-06-25 09:36
This issue is fixed in 5.2.6.3 version of FTV Stick Gen2

**Comment by kristurek** [comment] 2018-06-26 04:50
Hi
I tested FireStick with new version Fire OS 5.2.6.3 (606753920) and the same results, player crash after 5 seconds.

` MtkOmxVdec: [0xb865aaf8] Input picture is over MAX.
  MtkOmxVdec: [0xb865aaf8] Insert PTS error
  MtkOmxVdec: [0xb865aaf8] something wrong when decoding....
  MtkOmxVdec: [0xb865aaf8] MtkOmxVdecDecodeThread terminated pVdec=0xB865AAF8
  ACodec  : [OMX.MTK.VIDEO.DECODER.AVC] ERROR(0x80001008)`

`ExoPlayerImplInternal: Internal runtime error.
ExoPlayerImplInternal: java.lang.IllegalStateException
ExoPlayerImplInternal: 	at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
ExoPlayerImplInternal: 	at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:1055)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.drainOutputBuffer(MediaCodecRenderer.java:1064)
ExoPlayerImplInternal: 	at com.google.android.exoplayer2.mediacodec.MediaCodecRenderer.render(MediaCodecRenderer.java:599)`

New bugreport https://www.dropbox.com/s/uo1pe4lahkwl293/bugreport_tvp_hd_amazon_new.txt?dl=0

Please reopen issue

**Comment by peddisri** [comment] 2018-06-26 12:36
Sorry, my bad. Looks like the fix is going into next release, not 5.2.6.3. Apologize for the confusion.

**Comment by kristurek** [comment] 2018-08-29 14:26
Issue is fixed in 5.2.6.6, thanks very much for help

**Closed as completed** 2018-08-29 14:38 UTC
