### ISSUE TITLE
Can we integrate youtube API in Fireapp Builder? If No Can you please suggest the best approach to play the Youtube Urls

### ISSUE THREAD

**Issue by Maneesh528** [amzn/exoplayer-amazon-port#85] opened 2019-02-11 07:01 UTC
Hello Team, I am developing an App for Amazon FireTV by using Fireapp Builder. How can I play Youtube Urls in it ?

**Comment by rinoshs** [comment] 2019-02-13 13:55
Duplicate of Issue#84

**Closed as completed** 2019-02-13 13:54 UTC

**Comment by Maneesh528** [comment] 2019-02-15 07:38
Hi, I didn't receive any response from Issue #84, So I created a new ticket. 

Please respond to: **Can we integrate youtube API in Fireapp Builder? If No Can you please suggest the best approach to play the Youtube Urls** It's been to late, Requesting to please respond fast.
